name: GitHub Maven Build Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: STEP 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: STEP 2 - Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: STEP 3 - Build Maven Project
        run: mvn -B package --file pom.xml

      - name: STEP 4 - List Files
        run: |
          echo --------------------- Working Directory --------------------- 
          Get-ChildItem -Force
          echo --------------------- Target Directory --------------------- 
          cd target
          Get-ChildItem -Force
          
